### ISSUE TITLE
Hunk_freeTempMemory: bad magic

### ISSUE THREAD

**Issue by 10010101001** [suijingfeng/vkQuake3#5]
I come across this error when trying to run the game with Vulkan API. OpenGL does not cause this error.

**Comment by Vikingtons** [comment]
Do you have any steps to replicate this? What specs were you running on when this happened?

**Comment by 10010101001** [comment]
I used ioquake 3 vulkan renderer on urban terror. Quake 3 and most mods work fine with the renderer.

**Comment by nixguru** [comment]
I ran into this issue when running on a Raspberry Pi 4 and executing with Vulkan rendering enabled.  It would crash quickly with this error.  I had moved a bunch of additional PK3 files into the baseq3 directory so that I could play other maps. I then removed these extra files and left only the original pak0.pk3 + patched ioquake3 .pk3 files in the directory and it would start without issue.

**Comment by runlevel5** [comment]
@nixguru i know this issue is quite old but could you please provide the stacktrace with `gdb` if possible

**Comment by nixguru** [comment]
@runlevel5 I wish I could still help.  I don't have the platform anymore to be able to assist.

**Comment by blitztide** [comment]
Stacktrace of build on Linux using current latest commit, attempting to use VK renderer.

```
#0  Hunk_FreeTempMemory (buf=0x7fffc3574ee0) at code/qcommon/common.c:1842
#1  0x000055555559d3a8 in FS_FreeFile (buffer=0x7fffc3574ee0) at code/qcommon/files.c:1967
#2  0x00007fffc30159f0 in BuildSingleLargeBuffer (buffers=0x7fffffff5580, nShaderFiles=208, sum=2002781) at code/renderer_vulkan/R_FindShader.c:405
#3  0x00007fffc30160ee in ScanAndLoadShaderFiles () at code/renderer_vulkan/R_FindShader.c:558
#4  0x00007fffc3031ace in R_InitShaders () at code/renderer_vulkan/tr_shader.c:2213
#5  0x00007fffc3018026 in R_Init () at code/renderer_vulkan/tr_init.c:133
#6  0x00007fffc30181dc in RE_BeginRegistration (pGlCfg=0x555555d39968 <cls+966856>) at code/renderer_vulkan/tr_init.c:201
#7  0x0000555555572748 in CL_InitRenderer () at code/client/cl_main.c:3125
#8  0x00005555555727fe in CL_StartHunkUsers (rendererOnly=qfalse) at code/client/cl_main.c:3154
#9  0x0000555555595d4c in Com_Init (commandLine=0x7fffffffd680 "") at code/qcommon/common.c:2814
#10 0x0000555555624c93 in main (argc=1, argv=0x7fffffffdba8) at code/sys/sys_main.c:756

```

Looks like it is trying to free the same memory address twice

**Comment by blitztide** [comment]
Here's the contents of buffer at that point:
```
  0x7fffc356c538 "//cavalry bands\r\nmodels/players/athena/arms_cavalry_w\r\n{\r\n\t{\r\n\t\tmap models/players/athena/arms_cavalry_w.tga\r\n\t\trgbgen lightingDiffuse\r\n\t}\r\n\t{\r\n\t\tmap models/players/athena/arms_band.tga\r\n\t\tblendfunc G"..., 
  0x7fffc356cd98 "textures/terrain/rock_moss3_512\r\n{\r\n\t{\r\n\t  map\ttextures/terrain/rock_moss3_512.tga\r\n\r\n\t}\t\r\n\t{\r\n\t  map\t$lightmap\r\n\t  blendfunc gl_dst_color gl_src_color\r\n\t}\t\r\n}\r\n\r\ntextures/terrain/rock_moss4_512\r\n{\r\n\t"..., 
  0x7fffc356eca0 "\n// ink shader for maps\n// to use, add \"cel\" to shaderlist.txt\n// add a \"_celshader\" key to worldspawn entity with a value of \"cel/ink\"\n\ntextures/cel/ink\n{\n\tqer_editorimage gfx/colors/black.tga\n\t\n\tq3m"..., 
  0x7fffc356eeb8 "//", '=' <repeats 76 times>, "\n// shaders for ut_oildepot, a Urban Terror map by codemadeflesh\n//", '=' <repeats 55 times>..., 
  0x7fffc3574ee0 "textures/bbq2/coinwindow\r\n{\r\n\tqer_editorimage textures/bbq2/coinbird01.tga\r\n\t{\r\n\t\tanimMap .125 textures/bbq2/coinbird02.tga textures/bbq2/coinbird02.tga textures/bbq2/coinbird01.tga textures/bbq2/coin"..., 
  0x7fffc3574ee0 "textures/bbq2/coinwindow\r\n{\r\n\tqer_editorimage textures/bbq2/coinbird01.tga\r\n\t{\r\n\t\tanimMap .125 textures/bbq2/coinbird02.tga textures/bbq2/coinbird02.tga textures/bbq2/coinbird01.tga textures/bbq2/coin"..., 
  0x7fffc3575040 "\r\nmodels/weapons2/colt1911/colt1911_main\r\n\r\n{\r\n\t nomipmaps \r\n\t{\r\n\t\tmap models/weapons2/colt1911/colt1911_main.tga\r\n\t\trgbGen lightingDiffuse \r\n\r\n\t}\r\n\t{\r\n\t\tmap gfx/misc/specdot3b.jpg\r\n", ' ' <repeats 16 times>, "tc"..., 
  0x7fffc35753c0 "textures/urban_terror/nitesky2\r\n{\r\n\tsurfaceparm noimpact\r\n\tsurfaceparm nolightmap\r\n\tsurfaceparm sky\r\n\r\n\tq3map_sun .3 .3 .7 70 65 78\r\n\tq3map_surfacelight 60\r\n\tskyparms - 512 -\r\n\t{\r\n\t\tmap textures/urban"..., 
  0x7fffc3575e28 "textures/cow/hillf2\r\n{\r\n\tsurfaceparm noimpact\r\n\tsurfaceparm nolightmap\r\n\tsurfaceparm sky\r\n\tq3map_sun .3 .3 .7 70 65 78\r\n\tq3map_surfacelight 60\r\n\tq3map_globaltexture\r\n\tq3map_lightsubdivide 512\r\n\tskypar"..., 

```

**Comment by runlevel5** [comment]
@blitztide thanks for the trace but I am unable to re-produce the issue. Could you please provide further information on version of vulkan headers, linux and graphic cards / gpu driver?

**Comment by runlevel5** [comment]
@blitztide could you please give this port a go https://github.com/ioquake/ioq3/pull/861 to see if you still see the same issue?
